<a href="https://colab.research.google.com/github/gaolarry1987/MachineLearning-DeepLearning/blob/Practices/Practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import torch
import numpy as np

In [42]:
tensor_A = torch.rand(7,7)
tensor_A

tensor([[0.7695, 0.0378, 0.2239, 0.6772, 0.5274, 0.6325, 0.0910],
        [0.2323, 0.7269, 0.1187, 0.3951, 0.7199, 0.7595, 0.5311],
        [0.6449, 0.7224, 0.4416, 0.3634, 0.8818, 0.9874, 0.7316],
        [0.2814, 0.0651, 0.0065, 0.5035, 0.3082, 0.3742, 0.4297],
        [0.9729, 0.9739, 0.4533, 0.3499, 0.7428, 0.4601, 0.0242],
        [0.6630, 0.9787, 0.1037, 0.3920, 0.6084, 0.0928, 0.0719],
        [0.8733, 0.3230, 0.7917, 0.5447, 0.6220, 0.1668, 0.3932]])

In [43]:
tensor_B = torch.rand(1,7)
tensor_C = tensor_B.T
tensor_C

tensor([[0.8298],
        [0.7293],
        [0.3554],
        [0.5615],
        [0.8828],
        [0.0619],
        [0.8212]])

In [44]:
torch.matmul(tensor_A, tensor_C)

tensor([[1.7055],
        [2.1056],
        [2.8635],
        [1.2141],
        [2.5793],
        [2.1228],
        [2.4298]])

In [45]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(7,7)

print(tensor_A == tensor_C)

torch.matmul(tensor_A, tensor_C)

tensor([[True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True]])


tensor([[1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752],
        [1.5323, 1.5229, 1.2803, 1.3610, 0.9783, 1.3436, 1.0728],
        [1.9851, 1.2829, 1.9461, 1.6327, 1.6470, 1.8897, 1.0188],
        [1.6047, 1.9098, 2.3681, 2.3476, 1.6475, 1.9148, 1.4521],
        [1.4985, 0.9676, 1.6055, 1.1853, 1.1255, 1.4089, 0.5297],
        [1.4340, 1.2833, 2.1648, 2.2554, 1.3629, 1.6467, 1.0185],
        [0.9212, 1.1111, 1.4061, 1.7023, 1.3085, 1.4995, 0.7890]])

In [46]:
torch.cuda.is_available()

True

In [47]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device
torch.cuda.device_count()

1

In [48]:
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(4,4)
tensor_D
tensor_on_GPU = tensor_D.to(device)

In [49]:
torch.manual_seed(RANDOM_SEED)
tensor_E = torch.rand(4,4)
tensor_E_on_GPU = tensor_E.to(device)

print(tensor_on_GPU == tensor_E_on_GPU)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]], device='cuda:0')


In [50]:
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(2,3).to(device)
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(2,3).to(device)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[True, True, True],
        [True, True, True]], device='cuda:0')


In [51]:
random_tensor_B = random_tensor_B.T
torch.matmul(random_tensor_A, random_tensor_B)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [52]:
torch.min(random_tensor_A)

tensor(0.0290, device='cuda:0')

In [53]:
torch.max(random_tensor_A)

tensor(0.7006, device='cuda:0')

In [54]:
torch.min(random_tensor_B)

tensor(0.0290, device='cuda:0')

In [55]:
torch.max(random_tensor_B)

tensor(0.7006, device='cuda:0')

In [56]:
torch.argmin(random_tensor_A)

tensor(0, device='cuda:0')

In [57]:
torch.argmax(random_tensor_A)

tensor(5, device='cuda:0')

In [58]:
torch.argmin(random_tensor_B)

tensor(0, device='cuda:0')

In [59]:
torch.argmax(random_tensor_B)

tensor(5, device='cuda:0')

In [63]:
torch.manual_seed(7)
random_tensor_C = torch.rand(1,1,1,10)
print(random_tensor_C.shape)
random_tensor_D = random_tensor_C.squeeze()
print(random_tensor_D.shape)

torch.Size([1, 1, 1, 10])
torch.Size([10])
