<a href="https://colab.research.google.com/github/gaolarry1987/MachineLearning-DeepLearning/blob/Practices/Practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
tensor_A = torch.rand(7,7)
tensor_A

tensor([[0.5849, 0.4647, 0.4208, 0.8889, 0.0427, 0.7048, 0.7357],
        [0.1725, 0.1831, 0.5271, 0.4937, 0.1738, 0.4140, 0.0456],
        [0.1045, 0.1307, 0.7788, 0.7608, 0.5355, 0.4229, 0.2488],
        [0.0881, 0.7563, 0.6910, 0.9297, 0.3397, 0.7321, 0.1856],
        [0.6194, 0.8103, 0.2695, 0.6807, 0.3478, 0.5361, 0.8866],
        [0.1305, 0.3124, 0.5616, 0.0088, 0.6129, 0.8902, 0.1993],
        [0.0703, 0.9783, 0.9765, 0.3602, 0.7695, 0.0012, 0.9667]])

In [ ]:
tensor_B = torch.rand(1,7)
tensor_C = tensor_B.T
tensor_C

tensor([[0.0889],
        [0.2921],
        [0.3228],
        [0.7492],
        [0.0757],
        [0.9224],
        [0.1500]])

In [ ]:
torch.matmul(tensor_A, tensor_C)

tensor([[1.7532],
        [1.0108],
        [1.3367],
        [1.8772],
        [1.5425],
        [1.1882],
        [1.0815]])

In [ ]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(7,7)

print(tensor_A == tensor_C)

torch.matmul(tensor_A, tensor_C)

tensor([[True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True]])


tensor([[1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752],
        [1.5323, 1.5229, 1.2803, 1.3610, 0.9783, 1.3436, 1.0728],
        [1.9851, 1.2829, 1.9461, 1.6327, 1.6470, 1.8897, 1.0188],
        [1.6047, 1.9098, 2.3681, 2.3476, 1.6475, 1.9148, 1.4521],
        [1.4985, 0.9676, 1.6055, 1.1853, 1.1255, 1.4089, 0.5297],
        [1.4340, 1.2833, 2.1648, 2.2554, 1.3629, 1.6467, 1.0185],
        [0.9212, 1.1111, 1.4061, 1.7023, 1.3085, 1.4995, 0.7890]])

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device
torch.cuda.device_count()

1

In [ ]:
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(4,4)
tensor_D
tensor_on_GPU = tensor_D.to(device)

In [ ]:
torch.manual_seed(RANDOM_SEED)
tensor_E = torch.rand(4,4)
tensor_E_on_GPU = tensor_E.to(device)

print(tensor_on_GPU == tensor_E_on_GPU)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]], device='cuda:0')


In [ ]:
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(2,3).to(device)
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(2,3).to(device)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[True, True, True],
        [True, True, True]], device='cuda:0')


In [ ]:
random_tensor_B = random_tensor_B.T
torch.matmul(random_tensor_A, random_tensor_B)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [ ]:
torch.min(random_tensor_A)

tensor(0.0290, device='cuda:0')

In [ ]:
torch.max(random_tensor_A)

tensor(0.7006, device='cuda:0')

In [ ]:
torch.min(random_tensor_B)

tensor(0.0290, device='cuda:0')

In [ ]:
torch.max(random_tensor_B)

tensor(0.7006, device='cuda:0')

In [ ]:
torch.argmin(random_tensor_A)

tensor(0, device='cuda:0')

In [ ]:
torch.argmax(random_tensor_A)

tensor(5, device='cuda:0')

In [ ]:
torch.argmin(random_tensor_B)

tensor(0, device='cuda:0')

In [ ]:
torch.argmax(random_tensor_B)

tensor(5, device='cuda:0')