<a href="https://colab.research.google.com/github/gaolarry1987/MachineLearning-DeepLearning/blob/PyTorch-Fundamentals/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World!")


Hello World!


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [4]:
## Intro to Tensors

##Tensor represent data, multi-demension data.
##PyTorch tensors are created using `torch.Tensor()`

In [5]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#get tensor back as int
scalar.item()

7

In [8]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [20]:
TENSOR2 = torch.tensor([[[[1,2,3],
                          [4,5,6],
                          [7,8,9],
                          [10,11,12]]]])
TENSOR2

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]])

In [21]:
TENSOR2.ndim

4

In [22]:
TENSOR2.shape

torch.Size([1, 1, 4, 3])

In [23]:
### Random tensors
### Important, many nuural networks is full of random numbers
### start with random numbers -> look at the data -> update random data

In [24]:
#create a random tensor of size, shape

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2966, 0.9624, 0.1581, 0.3316],
        [0.0806, 0.2115, 0.6966, 0.8041],
        [0.3899, 0.2288, 0.5169, 0.0845]])

In [25]:
random_tensor.ndim

2

In [26]:
random_tensor.shape

torch.Size([3, 4])

In [27]:
# create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))#height, width, color
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [28]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
# create tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [31]:
# use torch.range()
one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor data-types
**Note** Tensor datatype is one of the 3 big erroes you will run into with PyTorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [33]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype(float32 or 16?)
                               device =None, # what device is your tensors on
                               requires_grad = False) # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [37]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.long)
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors
1.Tensors not right datatype - to get datatype from a tensor, can use 'tensor.dtype'

2.Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'

3.Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [38]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2191, 0.0072, 0.5448, 0.2409],
        [0.8813, 0.1788, 0.0464, 0.2556],
        [0.9165, 0.3164, 0.3417, 0.6762]])

In [39]:
print(some_tensor)
# Find out details about some_tensor


tensor([[0.2191, 0.0072, 0.5448, 0.2409],
        [0.8813, 0.1788, 0.0464, 0.2556],
        [0.9165, 0.3164, 0.3417, 0.6762]])


In [40]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating Tensors
-Tensor operations include:

-addition

-subtraction

-multiplication(element-wise)

-division

-matrix multiplication

In [41]:
# create a tensor
tensor3 = torch.tensor([1,2,3])
tensor3 + 10

tensor([11, 12, 13])

In [42]:
# multiply by 10
tensor3 * 10

tensor([10, 20, 30])

In [43]:
# Sub
tensor3 - 10

tensor([-9, -8, -7])

In [44]:
# try out PyTorch in-built functions
torch.mul(tensor3, 10)

tensor([10, 20, 30])

In [45]:
torch.add(tensor3,10)

tensor([11, 12, 13])

### Matrix Multiplication
1. Element-wise mul
2. Matrix mul(Dot product)

In [46]:
# Element-wise
print(tensor3, "*", tensor3)
print(f"Equals:{tensor3*tensor3}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [47]:
# Matrix Mul
%%time
torch.matmul(tensor3, tensor3)

CPU times: user 201 µs, sys: 874 µs, total: 1.08 ms
Wall time: 4.61 ms


tensor(14)

In [48]:
# Matrix mul by hand
%%time
val = 0
for i in range(len(tensor3)):
  val += tensor3[i] * tensor3[i]
print(val)

tensor(14)
CPU times: user 810 µs, sys: 0 ns, total: 810 µs
Wall time: 831 µs


### one of the most errors is shape erroes
two main rules for matrix mul

1 the inner dimension must match

2

In [49]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.7595, 0.1609, 0.7569],
        [0.4914, 0.2484, 0.4936],
        [0.2543, 0.3746, 0.2622]])

# To fix our tensor shape issue, we can manipulate the shape of one our tensors using transpose
Transpose switches the axes or dimension of a given tensor.


In [50]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

In [51]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [52]:
# 1. The Matrix mul operations works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")

print(f"New shapes: tensor_A = {tensor_A.shape}(same as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

torch.mm(tensor_A, tensor_B.T).shape


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2])(same as above), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


torch.Size([3, 3])

## Finding the min, max, mean, sum etc(tensor aggregation)

In [53]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [54]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [55]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [56]:
# torch.mean() function requires a tensor of float32 datatype
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [57]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional mi9n and max

In [58]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# Find the position in tensor that has the min value with argmin(), return position of index of the min

In [59]:
x.argmin(), x[0]

(tensor(0), tensor(0))

In [60]:
x.argmax(), x[9]

(tensor(9), tensor(90))

## Reshaping, stacking, squeezing and unsqueezing tensors
Reshape- reshape the tensor to a defined shape

view- return a view of an input tensor of certain shape but keep the same memory as the original torch.tensor

Stacking- combine multiple tensors on top of each other(vstack) or side by side(hstack)

Squeeze - remove all '1' dimensions from a tensor

Unsqueeze - add a '1' dimension to a target tensor

permute - Return a view of the input with dimensions permuted(Swapped) in a certain way

In [61]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [62]:
# Add an extra dimension
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [63]:
# change the view
z = x.view(1,9)
z.shape


torch.Size([1, 9])

In [64]:
# Changing z changes x(Because a view of a tensor shares the same memory)
z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [65]:
# Stack tensors on top of each other
x_stack = torch.stack([x,x,x,x], dim = 1)#vstack dim = 0, hstack dim = 1
x_stack

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [66]:
#torch.squeeze() - remove all single dimensions from a target tensor
print(f"Previous tensor: {x_reshape}")
print(f"Previous shape: {x_reshape.shape}")

# remove extra dimension from x_reshape
x_squeezed = x_reshape.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape:{x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape:torch.Size([9])


In [67]:
x_reshape.squeeze(), x_reshape.squeeze().shape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [68]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target:{x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")


Previous target:tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape:torch.Size([9])

New tensor:tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape:torch.Size([1, 9])


In [69]:
# torch.permute - rearange the dimensions of a target in a specific order
x_original = torch.rand(size=(224,224,3)) #Height, Width, color_channels

x_permuted = x_original.permute(2,0,1) # shift axis 0 -> 1, 1->2, 2->0
print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [70]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (Selecting data from tensors)
# Indexing with PyTorch is similar to indexing with NumPy

In [71]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
# Let's index on it
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
# Let's index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [74]:
#Let's index on the most inner bracket
x[0][2][2]

tensor(9)

In [75]:
# use":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [76]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [77]:
# Get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [78]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [79]:
# Index onx to return 9
x[:,2,2]

tensor([9])

In [80]:
# Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

### PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing lobrary.

Because of this, PyTorch has functionality to interact with it.

Data in NumPy, want it in PyTorch tensor -> 'torch.from_numpy(ndarray)'

PyTorch tensor -> NumPy -> torch.Tensor.numpy()



In [81]:
# NumPy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)# numpy -> torch default in float64 unless change
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [82]:
array.dtype

dtype('float64')

In [83]:
tensor.dtype

torch.float32

In [84]:
# Change the value of array, wgat will it do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [85]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [86]:
# Change the tensor, what will do to numpy?
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###Reproducbility (Trying to take random out of random)

how neural networks learns:
start with random numbers -> tensor operation -> update random numbers to try and make them of the data -> repeat

To reduce the randomness in neural networks and PyTorch comes the concept of a Random Seed

Essentially what the random seed does is "flavour" the randomness

In [88]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6795, 0.6074, 0.7828, 0.9571],
        [0.0210, 0.5456, 0.4956, 0.0201],
        [0.4219, 0.6440, 0.4830, 0.1257]])
tensor([[0.5496, 0.7686, 0.8062, 0.1042],
        [0.6290, 0.0864, 0.0603, 0.2671],
        [0.5898, 0.4046, 0.9959, 0.4162]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [90]:
# Make some random but reproduciable tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
