<a href="https://colab.research.google.com/github/gaolarry1987/MachineLearning-DeepLearning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World!")


Hello World!


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [ ]:
## Intro to Tensors

##Tensor represent data, multi-demension data.
##PyTorch tensors are created using `torch.Tensor()`

In [ ]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR2 = torch.tensor([[[[1,2,3],
                          [4,5,6],
                          [7,8,9],
                          [10,11,12]]]])
TENSOR2

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]])

In [ ]:
TENSOR2.ndim

4

In [ ]:
TENSOR2.shape

torch.Size([1, 1, 4, 3])

In [ ]:
### Random tensors
### Important, many nuural networks is full of random numbers
### start with random numbers -> look at the data -> update random data

In [ ]:
#create a random tensor of size, shape

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3934, 0.3565, 0.5021, 0.9398],
        [0.5896, 0.8141, 0.9989, 0.3646],
        [0.0520, 0.9791, 0.0447, 0.2525]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))#height, width, color
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
# use torch.range()
one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor data-types
**Note** Tensor datatype is one of the 3 big erroes you will run into with PyTorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype(float32 or 16?)
                               device =None, # what device is your tensors on
                               requires_grad = False) # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.long)
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors
1.Tensors not right datatype - to get datatype from a tensor, can use 'tensor.dtype'

2.Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'

3.Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7357, 0.0822, 0.5424, 0.1197],
        [0.1877, 0.9662, 0.5361, 0.0708],
        [0.0754, 0.0777, 0.7105, 0.6255]])

In [ ]:
print(some_tensor)
# Find out details about some_tensor


tensor([[0.7357, 0.0822, 0.5424, 0.1197],
        [0.1877, 0.9662, 0.5361, 0.0708],
        [0.0754, 0.0777, 0.7105, 0.6255]])


In [ ]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating Tensors
-Tensor operations include:

-addition

-subtraction

-multiplication(element-wise)

-division

-matrix multiplication

In [ ]:
# create a tensor
tensor3 = torch.tensor([1,2,3])
tensor3 + 10

tensor([11, 12, 13])

In [ ]:
# multiply by 10
tensor3 * 10

tensor([10, 20, 30])

In [ ]:
# Sub
tensor3 - 10

tensor([-9, -8, -7])

In [ ]:
# try out PyTorch in-built functions
torch.mul(tensor3, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor3,10)

tensor([11, 12, 13])

### Matrix Multiplication
1. Element-wise mul
2. Matrix mul(Dot product)

In [ ]:
# Element-wise
print(tensor3, "*", tensor3)
print(f"Equals:{tensor3*tensor3}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
# Matrix Mul
%%time
torch.matmul(tensor3, tensor3)

CPU times: user 188 µs, sys: 0 ns, total: 188 µs
Wall time: 196 µs


tensor(14)

In [ ]:
# Matrix mul by hand
%%time
val = 0
for i in range(len(tensor3)):
  val += tensor3[i] * tensor3[i]
print(val)

tensor(14)
CPU times: user 1.79 ms, sys: 0 ns, total: 1.79 ms
Wall time: 1.8 ms


### one of the most errors is shape erroes
two main rules for matrix mul

1 the inner dimension must match

2

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.1582, 0.6439, 0.4052],
        [0.7667, 0.7768, 0.6675],
        [0.3948, 0.4114, 0.3500]])

# To fix our tensor shape issue, we can manipulate the shape of one our tensors using transpose
Transpose switches the axes or dimension of a given tensor.


In [ ]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# 1. The Matrix mul operations works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")

print(f"New shapes: tensor_A = {tensor_A.shape}(same as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

torch.mm(tensor_A, tensor_B.T).shape


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2])(same as above), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


torch.Size([3, 3])

## Finding the min, max, mean, sum etc(tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# torch.mean() function requires a tensor of float32 datatype
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional mi9n and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# Find the position in tensor that has the min value with argmin(), return position of index of the min

In [ ]:
x.argmin(), x[0]

(tensor(0), tensor(0))

In [ ]:
x.argmax(), x[9]

(tensor(9), tensor(90))

## Reshaping, stacking, squeezing and unsqueezing tensors
Reshape- reshape the tensor to a defined shape

view- return a view of an input tensor of certain shape but keep the same memory as the original torch.tensor

Stacking- combine multiple tensors on top of each other(vstack) or side by side(hstack)

Squeeze - remove all '1' dimensions from a tensor

Unsqueeze - add a '1' dimension to a target tensor

permute - Return a view of the input with dimensions permuted(Swapped) in a certain way

In [ ]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [97]:
# change the view
z = x.view(1,9)
z.shape


torch.Size([1, 9])

In [99]:
# Changing z changes x(Because a view of a tensor shares the same memory)
z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [109]:
# Stack tensors on top of each other
x_stack = torch.stack([x,x,x,x], dim = 1)#vstack dim = 0, hstack dim = 1
x_stack

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [114]:
#torch.squeeze() - remove all single dimensions from a target tensor
print(f"Previous tensor: {x_reshape}")
print(f"Previous shape: {x_reshape.shape}")

# remove extra dimension from x_reshape
x_squeezed = x_reshape.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape:{x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape:torch.Size([9])


In [113]:
x_reshape.squeeze(), x_reshape.squeeze().shape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [115]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target:{x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")


Previous target:tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape:torch.Size([9])

New tensor:tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape:torch.Size([1, 9])


In [117]:
# torch.permute - rearange the dimensions of a target in a specific order
x_original = torch.rand(size=(224,224,3)) #Height, Width, color_channels

x_permuted = x_original.permute(2,0,1) # shift axis 0 -> 1, 1->2, 2->0
print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])
